[theme]
primaryColor = "#808000"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1A1A1A"
textColor = "#F0F0F0"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
